### ISSUE TITLE
use of attributedText = crash

### ISSUE THREAD

**Issue by arsonik** [glaszig/SZTextView#28] opened 2014-12-11 13:33 UTC
Hi,

First thank you for your work on that great drop in replacement  !
But for compatibility purposes can it still work when we try to assign a string value to attributedText ?
```
self.textView.text = "Simple text" // work
self.textView.attributedText = NSAttributedString(string: "NSAttributedString") // crash
```
probably because the all placeholder, kvo... is based on that attributed string ?
Well that would be really nice of you :)

Cheers

**Comment by glaszig** [comment] 2015-02-10 13:56
finally got around to dig farther into this. in the `tableview` branch i added a table view and custom cell with an `SZTextView` instance inside of it to the demo. i set the `text` in `-tableView:cellForRowAtIndexPath:` and _still_ it doesn't crash. both on the 8.1 and 7.0 sdk.

also, the `text` and `attributedText` observers get triggered sequentially at the same time because this is what `UITextView` does. from [the docs](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITextView_Class/index.html#//apple_ref/occ/instp/UITextView/text):

> [...] In iOS 6 and later, assigning a new value to this property also replaces the value of the attributedText property with the same text, albeit without any inherent style attributes. [...]

if you're still having an issue, please provide a small sample app that reproduces the behavior you're experiencing.

fwiw, i'm using `SZTextView` in the same way in [Cocktailicious](http://www.cocktailiciousapp.com/) and don't have an issue.

**Comment by Maleandr** [comment] 2015-02-10 17:58
I have same problem. It'm loading controller from storyboard (instaniateViewController..) and then setting SZTextview text property and get same error [NSNull string]

**Comment by glaszig** [comment] 2015-02-10 18:19
@Maleandr as much as i would like to resolve this issue for all of you i am quite constrained in terms of time i'm able to devote to it these days. that said, a small sample project would be very greatly appreciated.

**Comment by Maleandr** [comment] 2015-02-10 21:50
I understand that. I will try somehow split it from my project. I just wonder if you test it in Swift or Objective-C?

**Comment by glaszig** [comment] 2015-02-10 23:21
objc. but both languages compile down to the same runtime so i'd be very surprised if that's the issue.

**Comment by yakubbaev** [comment] 2015-05-08 11:17
+1

**Comment by glaszig** [comment] 2015-12-25 17:28
alright. i'm still at a loss here. since nobody provided a simple demo app i'll close this one. feel free to reopen if need be (and you can replicate the behavior in a demo app). merry new year.

**Closed by glaszig** 2015-12-25 17:28 UTC
