### ISSUE TITLE
Usage with Interface Builder

### ISSUE THREAD

**Issue by mhaseebkhan** [glaszig/SZTextView#37] opened 2015-05-08 14:37 UTC
I am using SZTextView with CocoaPods in one of the projects I am working on. I added the SZTextView via InterfaceBuilder in a XIB.

When I build the app, I am getting the following warnings with a red exclamation mark. My XCode Version is 6.3(6D570).

>error: IB Designables: Failed to render instance of SZTextView: Failed to load designables from path (null)
>error: IB Designables: Failed to update auto layout status: Failed to load designables from path (null)

Please suggest.

**Comment by glaszig** [comment] 2015-05-11 23:52
can you reproduce this behavior reliably?

**Comment by sarbogast** [comment] 2015-05-12 15:11
I'm having the exact same issue right now.

**Comment by dwag3** [comment] 2015-05-12 16:15
I'm also having this issue but build and run still succeed.

**Comment by glaszig** [comment] 2015-05-12 18:02
please check if the issue can be resolved as in #35.

**Comment by Ricardo1980** [comment] 2015-05-19 16:43
Hello!
When using the use_framework! flag, I receive "embedded dylibs/frameworks only run on iOS 8 or later".
It seems iOS8 is required for that feature.
But I'd like my project work under iOS7.
Does anyone have any suggestion?
Thanks in advance.

**Comment by glaszig** [comment] 2015-05-19 19:06
@Ricardo1980 can you build & run w/o `use_framework!`? the IBDesignable issue seems to be an Xcode bug. but if you can build anyway you should not be bothered by the warning. (i know, i know, this not a solution for the long run)

**Comment by Ricardo1980** [comment] 2015-05-25 16:02
@glaszig Now it's working, not sure about the reason...

**Comment by Ricardo1980** [comment] 2015-11-01 09:07
Yes. I can build the app. 

Enviado desde mi iPhone.

**Comment by dexcell** [comment] 2015-11-01 09:45
I'm having the same issue, and it's looks like can be fixed by adding `use_frameworks!` on pod file

**Comment by codwam** [comment] 2015-11-13 04:49
It's actually a problem in OS X 10.10, xcode6.4 .....
And use_framework! is not support for iOS 7...

**Closed** 2015-12-25 17:24 UTC
